<?php
	
use Drupal\webform\WebformSubmissionForm;

use Drupal\Core\Form\FormStateInterface;
// use Drupal\Core\webform\Entity\WebformSubmissionInterface as WebformSubmission;
/** 
 * Goto step/page in form.
 *
 * @param string $goto_step
 * @param array $pages
 * @param object $form_state
 *
 */
function goto_step($goto_step, $pages, \Drupal\Core\Form\FormStateInterface $form_state){
  // Convert associative array to index for easier manipulation.
  $all_keys = array_keys($pages);
  $goto_destination_page_index = array_search($goto_step, $all_keys);
  if($goto_destination_page_index > 0){
    // The backend pointer for page will add 1 so to go our page we must -1.
    $form_state->set('current_page', $all_keys[$goto_destination_page_index]);
  }
  else{
    // Something went wrong.
  }
}

function custom_reset(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
    // Delete save draft.
       // Reset user input but preserve form tokens.
    $form_state->setUserInput(array_intersect_key($form_state->getUserInput(), [
      'form_build_id' => 'form_build_id',
      'form_token' => 'form_token',
      'form_id' => 'form_id',
    ]));
    // Reset values.
    $form_state->setValues([]);
    // Reset current page.
    $storage = $form_state->getStorage();
//     unset($storage['current_page']);
    $form_state->setStorage($storage);
    // Rebuild the form.
    $form_state->setRebuild(true);
}
  
/**
 * Implements hook_webform_submission_form_alter().
 */
function biz_iamlobbyist_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id !== 'webform_submission_lobbyist_finder_modal_add_form') {
    return;
  }

  // The following line is only needed if you allow drafts (manual or auto-save).
  //_lobbyist_finder_submit_page($form, $form_state);
  $form['actions']['wizard_next']['#submit'][] = '_lobbyist_finder_submit_page';
  $form['actions']['wizard_prev']['#submit'][] = '_lobbyist_finder_prev_page';
  $form_state->addCleanValueKey(
	['no',
	'select_one_option',
	'are_you_option',
	'are_you_option_1',
	'are_you_option_2',
	'are_you_option_3',
	'are_you_option_4',
	'are_you_option_5',
	'are_you_option_6',
	'are_you_option_7',
	'are_you_option_8',
	'are_you_option_9',
	'are_you_option_10',
	'are_you_option_12' ]
  );
}

function _lobbyist_finder_submit_page(array &$form, FormStateInterface $form_state) {
  // Conditional logic goes here.
  //dsm($form_state->getValues());
  $curent_values = $form_state->getValues();
  $pages = $form_state->get('pages');
  $webform_submission = $form_state->getFormObject()->getEntity();
  $current_page = $webform_submission->getCurrentPage();
  //dsm($current_page);
  if (($curent_values['are_you_option'] == 'Yes' && $current_page == 'page_6_1') || 
  		($curent_values['are_you_option_1'] == 'Yes' && $current_page == 'page_6_2') || 
  		($curent_values['are_you_option_2'] == 'Yes' && $current_page == 'page_6_3') || 
  		($curent_values['are_you_option_3'] == 'Yes' && $current_page == 'page_6_4') || 
  		($curent_values['are_you_option_4'] == 'Yes' && $current_page == 'page_6_5') || 
  		($curent_values['are_you_option_5'] == 'Yes' && $current_page == 'page_6_6') || 
  		($curent_values['are_you_option_6'] == 'Yes' && $current_page == 'page_7') || 
  		($curent_values['are_you_option_12'] == 'Yes' && $current_page == 'page_8')) {
	$page_name = 'page_8';
	goto_step($page_name, $pages, $form_state);
  }

  if (($curent_values['are_you_option_7'] == 'Yes' && $current_page == 'page_10') || 
  		($curent_values['are_you_option_8'] == 'Yes' && $current_page == 'page_11') || 
  		($curent_values['are_you_option_9'] == 'Yes' && $current_page == 'page_12') || 
  		($curent_values['are_you_option_10'] == 'Yes' && $current_page == 'final_page')) {
	$page_name = 'final_page';
	goto_step($page_name, $pages, $form_state);
  }

  
}

function _lobbyist_finder_prev_page(array &$form, FormStateInterface $form_state) {
  // Conditional logic goes here.
  //dsm($form_state->getValues());
  $curent_values = $form_state->getValues();
  $pages = $form_state->get('pages');
  $webform_submission = $form_state->getFormObject()->getEntity();
  $current_page = $webform_submission->getCurrentPage();
//   kint($curent_values);
//   dsm($form_state);
//   custom_reset($form, $form_state);
  //ToDo: We can clean values OR back to the last answered option
  if ($current_page == 'page_7') {
	$page_name = 'page_5';
	goto_step($page_name, $pages, $form_state);
    
//     $form_state->cleanValues();

  }
  if ($current_page == 'page_12') {
	$page_name = 'page_8';
	goto_step($page_name, $pages, $form_state);
  }
}