<?php
	


/**
 * Implements hook_local_tasks_alter().
 */
function biz_lobbyist_registration_local_tasks_alter(&$local_tasks) {
  unset($local_tasks['user.register']);
}


/**
 * Implements hook_menu_local_tasks_alter().
 */
function biz_lobbyist_registration_menu_local_tasks_alter(&$data, $route_name) {
    foreach ($data['tabs'][0] as $type => &$tab) {
        // ToDo: compare with id or any value that will no change with language
        // ToDo: Add t to translate
        if ($tab['#link']['title'] == 'Create new In-house lobbyist account') {
            $tab['#link']['title'] = 'Register as In-house lobbyist';
        }
        if ($tab['#link']['title'] == 'Create new Consultant lobbyist account') {
            $tab['#link']['title'] = 'Register as Consultant lobbyist';
        }
        unset($tab);
    }
}

