<?php
	

use Drupal\Core\Url;
/**
 * Implements hook_local_tasks_alter().
 */
function biz_lobbyist_registration_local_tasks_alter(&$local_tasks) {
  unset($local_tasks['user.register']);
}


/**
 * Implements hook_menu_local_tasks_alter().
 */
function biz_lobbyist_registration_menu_local_tasks_alter(&$data, $route_name) {

	$new_tab['#link']['title'] = "I Don't know";
	$new_tab['#link']['url'] = Drupal\Core\Url::fromUri('internal:/form/lobbyist-finder-modal');
	$new_tab['#theme'] = "menu_local_task";
	$new_tab['#active'] = FALSE;
	$new_tab['#access'] = $data['tabs'][0]['multiple_registration.local_tasks:in_house_lobbyist']['#access'];
	$data['tabs'][0]['multiple_registration.local_tasks:modal_lobbyist'] = $new_tab;

    foreach ($data['tabs'][0] as $type => &$tab) {
	    
        // ToDo: compare with id or any value that will no change with language
        // ToDo: Add t to translate
        if ($tab['#link']['title'] == 'Create new In-house lobbyist account') {
            $tab['#link']['title'] = 'Register as In-house lobbyist';
        }
        if ($tab['#link']['title'] == 'Create new Consultant lobbyist account') {
            $tab['#link']['title'] = 'Register as Consultant lobbyist';
            
        }
        if ($tab['#link']['title'] == 'Reset your password') {
            $tab['#link']['title'] = 'Forgot your password?';
        }
        if ($tab['#link']['title'] == "I Don't know") {
	        $tab['#link']['localized_options']['attributes']['class'][] = 'webform-dialog button';
	        $tab['#link']['localized_options']['attributes']['data-dialog-options'][] = '{"width":650,"height":500}';
        }
        unset($tab);
    }
}

// <?php
	


/**
 * Implements hook_local_tasks_alter().
 */
/*
function biz_lobbyist_registration_local_tasks_alter(&$local_tasks) {
  unset($local_tasks['user.register']);
}
*/


/**
 * Implements hook_menu_local_tasks_alter().
 */
/*
function biz_lobbyist_registration_menu_local_tasks_alter(&$data, $route_name) {
	
    foreach ($data['tabs'][0] as $type => &$tab) {
        // ToDo: compare with id or any value that will no change with language
        // ToDo: Add t to translate
        if ($tab['#link']['title'] == 'Create new In-house lobbyist account') {
            $tab['#link']['title'] = 'Register as In-house lobbyist';
            $new_tab = $tab;
        }
        if ($tab['#link']['title'] == 'Create new Consultant lobbyist account') {
            $tab['#link']['title'] = 'Register as Consultant lobbyist';
        }
        if ($tab['#link']['title'] == 'Reset your password') {
            $tab['#link']['title'] = 'Forgot your password?';
        }
        unset($tab);
    }
    $new_tab['#link']['title'] = "I Don't know";
    $new_tab['#link']['url'] = Url::fromUri('/form/lobbyist-finder-modal');
    kint($data['tabs'][0]);
    $data['tabs'][0][] = $new_tab;

}
*/

