name: Config Entity Revisions
description: Allows configuration entities in Drupal 8.5+ to have revisions.
package: api
type: module
# core: 8.x
dependencies:
  - content_moderation
  - diff
  - serialization

# Information added by Drupal.org packaging script on 2018-11-30
version: '8.x-1.3'
core: '8.x'
project: 'config_entity_revisions'
datestamp: 1543551784
