<?php
	
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Drupal\biz_webforms\Entity\BizWebformSubmission;

/*
function get_endpoint(Request $request) {

	$response['data'] = $request->getContent();
	$response['method'] = 'GET';

	return new JsonResponse( $response );
}
*/

/**
 * Execute the api
 */
/*
function get_endpoint($url, $data = array(), $method, $headers = array() ) {
  //Creating a httpClient Object.
  $client = \Drupal::httpClient();
  try {
    $request_options = [];
    if(!empty($headers)){
      $request_options =  array('headers' => $headers);   
    }
    if(!empty($data)){
      $request_options['json'] = $data;
    }
    $response = $client->$method($url, $request_options);
    return ["code" => $response->getStatusCode(), "message" => $response->getBody()->getContents()];
  }
  catch (\Exception $e) {
   if ($e->hasResponse()) {
      $response = $e->getResponse()->getBody();
      return ["code" => 400, "message" => $response];
    }
  }
}
*/
  
/*
function biz_webforms_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
	if ($form_id == "webform_submission_add_an_in_house_lobbyust_to_your_node_9_add_form") {
// 	 	
	 	$url = 'http://pr-14-lobbyist-frontend.pantheonsite.io/json/user/edgarallanglez@gmail.com';
	 	$response = get_endpoint($url, [], "GET", []);
	 	$data = json_decode($response["message"])[0];
	 	$form["elements"]["organization_header"]["#text"] = '<p>' . 'LEGAL ORGANIZATION' . '</p>' 
       . '<p>' . $data->field_legal_organization . '</p> '
       . '<p>' . 'OPERATING ORGANIZATION' . '</p> '
       . '<p>' . $data->field_operating_organization . '</p> '
       . '<p>' . 'ADDRESS' . '</p> '
       . '<p>' . $data->field_street_address_address_line1 . '</p> '
       . '<p>' . 'CITY OR TOWN' . '</p> '
       . '<p>' . $data->field_street_address_locality . '</p> '
        . '<p>' . 'COUNTRY' . '</p> '
       . '<p>' . $data->field_street_address_country_code . '</p> ';
       kint($data);
 	}
}
*/




