<?php

/**
 * @file
 * Provides form alter hooks to hide Webform global, form, and element settings.
 */

use Drupal\Core\Form\FormStateInterface;

function webform_elements_form_webform_ui_element_type_select_form_alter(
  &$form,
  FormStateInterface $form_state, $form_id) {
  $not_display = ["webform_address", "webform_contact", "webform_link",
    "webform_location_places", "webform_name", "webform_telephone",
    "webform_custom_composite", "managed_file", "webform_audio_file",
    "webform_document_file", "webform_video_file", "webform_image_file"];
  foreach ($form as $key => $value) {
    foreach ($not_display as $category => $type) {
      if (isset($value['elements']) && isset($value['elements'][$type])) {
        unset($form[$key]['elements'][$type]);
      }
    }
  }
}
