registration_url_api: 'http://pr-14-lobbyist-frontend.pantheonsite.io/entity/user?_format=json'
validate_email_url_api: 'http://pr-14-lobbyist-frontend.pantheonsite.io/api/users?_format=json&email="'
in_house_lobbyist_welcome_mail: ''
consultant_lobbyist_welcome_mail: ''
base_url: 'http://pr-14-lobbyist-frontend.pantheonsite.io/'
