multiple_registration_path_in_house_lobbyist: in-house-registration
multiple_registration_url_in_house_lobbyist: /user/register/in_house_lobbyist
multiple_registration_hidden_in_house_lobbyist: 0
multiple_registration_form_mode_register_in_house_lobbyist: register
multiple_registration_form_mode_edit_in_house_lobbyist: register
multiple_registration_path_consultant_lobbyist: consultant-registration
multiple_registration_url_consultant_lobbyist: /user/register/consultant_lobbyist
multiple_registration_hidden_consultant_lobbyist: 0
multiple_registration_form_mode_register_consultant_lobbyist: register
multiple_registration_form_mode_edit_consultant_lobbyist: register
