favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://pr-8-lobbyist-frontend.pantheonsite.io/themes/contrib/wxt_bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  wxt_bootstrap: 8000
  wxt_lobbyist: 8000
