schemas:
  bootstrap: 8000
  wxt_bootstrap: 8000
  wxt_lobbyist: 8000
modal_jquery_ui_bridge: 0
_core:
  default_config_hash: mO7mxem0JY6zvAroR3ebmv8PCghq7rhAHpmoBlTnb9o
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://pr-10-lobbyist-frontend.pantheonsite.io/themes/contrib/wxt_bootstrap/favicon.ico'
  use_default: true
wxt_skip_link_primary_text: 'Skip to main content'
wxt_skip_link_secondary_text: 'Skip to "About this site"'
wxt_gcweb_cdn_footer_url: ''
table_responsive: '-1'
region_wells:
  branding: ''
  navbar: ''
  navigation: ''
  search_bar: ''
  site_alert: ''
  highlighted: ''
  header: ''
  help: ''
  inline_arlert: ''
  content: ''
  page_form: ''
  sidebar: ''
  sidebar_sticky: ''
  featured: ''
  footer_top: ''
  footer: ''
cdn_provider: jsdelivr
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
logo:
  path: 'public://Screen Shot 2019-11-01 at 1.18.59 PM_0.png'
  url: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
