# Schema for the configuration files of the OpenID Connect REST module.
# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

openid_connect_rest.authorization_mapping.*:
  type: mapping
  label: 'Authorization mapping'
  mapping:
    id:
      type: string
      label: 'Authorization Mapping ID'
    authorization_code:
      type: string
      label: 'Authorization Code'
    state_token:
      type: string
      label: 'State Token'
    user_sub:
      type: string
      label: 'User Sub'
    expires:
      type: string
      label: 'Expires'

openid_connect_rest.state_token.*:
  type: mapping
  label: 'Authorization mapping'
  mapping:
    id:
      type: string
      label: 'State Token ID'
    state_token:
      type: string
      label: 'State Token'
    expires:
      type: string
      label: 'Expires'
